name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Clean workspace
        run: |
          rm -rf deccord

      - name: Clone Deccord repository
        run: |
          git clone https://github.com/Deccord/deccord.git
          cd deccord
          chmod -R 777 .

      - name: Setup dependencies for macOS
        run: |
          brew install automake cmake curl libtool pkg-config python3 bison berkeley-db@4 openssl boost

      - name: Build depends
        run: |
          cd deccord
          cd depends
          # Add compiler flags to handle Boost compilation
          export CXXFLAGS="-Wno-error=enum-constexpr-conversion"
          export CPPFLAGS="-Wno-error=enum-constexpr-conversion"
          # Build dependencies with warning suppression
          make -j$(sysctl -n hw.ncpu) HOST=x86_64-apple-darwin BOOST_CXXFLAGS="-Wno-error"
          cd ..

      - name: Build Deccord for macOS
        run: |
          cd deccord
          ./autogen.sh
          export BDB_PREFIX="$(brew --prefix berkeley-db@4)"
          # Configure with proper flags
          CONFIG_SITE=$PWD/depends/x86_64-apple-darwin/share/config.site ./configure --prefix=/ \
            --disable-tests --disable-bench --enable-static \
            CXXFLAGS="-Wno-error=enum-constexpr-conversion"
          make -j$(sysctl -n hw.ncpu)

      - name: Strip Binaries
        run: |
          cd deccord
          strip src/deccordd src/deccord-cli src/deccord-tx src/qt/deccord-qt

      - name: Create Release Structure
        run: |
          cd deccord
          mkdir -p deccord-20.0.1-x86_64-apple-darwin/bin
          cp src/deccordd src/deccord-cli src/deccord-tx src/qt/deccord-qt deccord-20.0.1-x86_64-apple-darwin/bin/
          tar -czvf deccord-20.0.1-x86_64-apple-darwin.tar.gz deccord-20.0.1-x86_64-apple-darwin
          zip -r deccord-20.0.1-x86_64-apple-darwin.zip deccord-20.0.1-x86_64-apple-darwin

      - name: Upload macOS Build Artifact (tar.gz)
        uses: actions/upload-artifact@v4
        with:
          name: deccord-20.0.1-x86_64-apple-darwin-tar
          path: deccord/deccord-20.0.1-x86_64-apple-darwin.tar.gz

      - name: Upload macOS Build Artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: deccord-20.0.1-x86_64-apple-darwin-zip
          path: deccord/deccord-20.0.1-x86_64-apple-darwin.zip

      - name: Upload Partial Build Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: partial-build-mac-${{ github.run_id }}
          path: deccord/src
