name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for macOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Clean workspace
        run: |
          rm -rf deccord

      - name: Clone Deccord repository
        run: |
          git clone https://github.com/Deccord/deccord.git
          cd deccord
          chmod -R 777 .

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git
          sudo apt-get install -y cmake libcap-dev libz-dev libbz2-dev python3-dev
          sudo apt-get install -y g++-multilib gcc-multilib binutils-gold
          sudo apt-get install -y clang llvm-dev libclang-dev libedit-dev

      - name: Build depends
        run: |
          cd deccord
          cd depends
          make HOST=x86_64-apple-darwin -j$(nproc)
          cd ..

      - name: Build Deccord for macOS
        run: |
          cd deccord
          ./autogen.sh
          CONFIG_SITE=$PWD/depends/x86_64-apple-darwin/share/config.site ./configure --prefix=/ \
            --disable-tests --disable-bench --enable-static \
            --disable-shared
          make -j$(nproc)

      - name: Strip Binaries
        run: |
          cd deccord
          x86_64-apple-darwin-strip src/deccordd src/deccord-cli src/deccord-tx src/qt/deccord-qt

      - name: Create Release Structure
        run: |
          cd deccord
          mkdir -p deccord-20.0.1-x86_64-apple-darwin/bin
          cp src/deccordd src/deccord-cli src/deccord-tx src/qt/deccord-qt deccord-20.0.1-x86_64-apple-darwin/bin/
          tar -czvf deccord-20.0.1-x86_64-apple-darwin.tar.gz deccord-20.0.1-x86_64-apple-darwin
          zip -r deccord-20.0.1-x86_64-apple-darwin.zip deccord-20.0.1-x86_64-apple-darwin

      - name: Upload macOS Build Artifact (tar.gz)
        uses: actions/upload-artifact@v4
        with:
          name: deccord-20.0.1-x86_64-apple-darwin-tar
          path: deccord/deccord-20.0.1-x86_64-apple-darwin.tar.gz

      - name: Upload macOS Build Artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: deccord-20.0.1-x86_64-apple-darwin-zip
          path: deccord/deccord-20.0.1-x86_64-apple-darwin.zip

      - name: Upload Partial Build Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: partial-build-mac-${{ github.run_id }}
          path: deccord/src
